### ISSUE TITLE
A small question

### ISSUE THREAD

**Issue by studylessshape** [egmkang/local_ipaddress#1]
This is a segment made me doubt.
Why do it need  to connect the ip `8.8.8.8:80` after bind ip `0.0.0.0:0`?

**Comment by egmkang** [comment]
@studylessshape 

第8章 基本udp套接字编程 186
8.1 概述 186
8.2 recvfrom和sendto函数 187
8.3 udp回射服务器程序：main函数 187
8.4 udp回射服务器程序：dg_echo函数 188
8.5 udp回射客户程序：main函数 190
8.6 udp回射客户程序：dg_cli函数 190
8.7 数据报的丢失 191
8.8 验证接收到的响应 191
8.9 服务器进程未运行 193
8.10 udp程序例子小结 194
8.11 udp的connect函数 196
8.12 dg_cli函数（修订版） 199
8.13 udp缺乏流量控制 200
8.14 udp中的外出接口的确定 203
8.15 使用select函数的tcp和udp回射服务器程序 204
8.16 小结 206

UNP 8.14
